taco:
  orders:
    pageSize: 10

spring:
  data:
    rest:
      base-path: /api

  jms:
    template:
      default-destination: tacocloud.order.queue

  artemis:
    host: localhost
    port: 61616
    user: tacoweb
    password: letm31n
    embedded:
      enabled: false

  rabbitmq:
    template:
      receive-timeout: 30000
    exchange: tacocloud.orders
    routing-key: kitchens.central

  kafka:
    template:
    default-topic: tacocloud.orders.topic
