taco:
  orders:
    pageSize: 10

spring:
  data:
    rest:
      base-path: /api

  jms:
    template:
      default-destination: tacocloud.order.queue

  artemis:
    host: localhost
    port: 61616
    user: tacoweb
    password: letm31n
    embedded:
      enabled: false